name: Docker Image CI To GitHub Packages

on:
  workflow_run:
    workflows: ["Bump Version"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in and fetch the version info
      run: |
        git config --global user.email "github+actions@gmail.com"
        git config --global user.name "Actions"
        git fetch --tags

    - name: Get bumped version
      # (git tag --sort=-v:refname --list "v[0-9]*" | head -n 1 | cut -c 2-)
      # ${(${GITHUB_REF#refs/*/}"):1}
      # run: echo "VERSION=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1 | cut -c 2-)" >> $GITHUB_ENV
      run: echo VERSION=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1 | cut -c 2-) > $GITHUB_ENV
      # shell: bash

    - name: Docker Login
      run: echo ${{ secrets.GHCR_TOKEN }}| docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

    - name: Build The Docker Image

      run: |
        docker build --tag ghcr.io/${{ secrets.GHCR_USER }}/proxy.naumofftech:${{ env.VERSION }} .

    - name: Push The Image
      run: docker push ghcr.io/${{ secrets.GHCR_USER }}/proxy.naumofftech:${{ env.VERSION }}
