version: '3.9'

services:
  minister:
    # Grab an image from the private container registry
    image: 10.0.0.12:5000/core
    tty: true
    stdin_open: true
    ports:
      - target: 8080
        published: 8080
        mode: host
    deploy:
      # replicas: 2
      # update_config:
      #   parallelism: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == worker

  serf:
    image: ${SERF_IMAGE}
    tty: true
    stdin_open: true
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    secrets:
      - site_cert
      - site_key
      - site_chain
    volumes:
      - type: "bind"
        source: ./certmaster/verify
        target: /var/www/certbot
    depends_on:
      - minister
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  site_cert:
    file: ./certmaster/certs/fullchain.pem
    name: site_cert_v${CERT_MD5}
  site_key:
    file: ./certmaster/certs/privkey.pem
    name: site_key_v${KEY_MD5}
  site_chain:
    file: ./certmaster/certs/chain.pem
    name: site_chain_v${CHAIN_MD5}
