version: '3.9'

services:
  minister:
    image: ${MINISTER_IMAGE}
    tty: true
    stdin_open: true
    ports:
      - target: 8080
        published: 8080
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == worker

  serf:
    tty: true
    stdin_open: true
    image: ${SERF_IMAGE}
    ports:
      - target: 80
        published: 80
        # mode: host
      - target: 443
        published: 443
        # mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
