name: Bump Version

on:
  push:
    branches-ignore:
      - dev
      - prod-server
      - bootstrap-implement

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in and fetch the version info
      run: |
        git config --global usxer.email "github+actions@gmail.com"
        git config --global user.name "Actions"
        git fetch --tags

    - name: Bump the version
      run: |
        set -e

        # Retrieve the latest version number
        git fetch --tags
        oldv=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1)

        # Remove the 'v' character from version
        oldv=${oldv:1}

        echo "oldv: $oldv"

        # If there is no version, start at 0.0.0
        if [ -z "$oldv" ]; then
        echo "No existing version, starting at 0.0.0"
        oldv="0.0.0"
        fi

        # Run awk script to increase version number
        newv=$(awk 'BEGIN{
            print(inc(ARGV[1]))
        }

        function inc(s,    a, len1, len2, len3, head, tail)
        {
            split(s, a, ".")

            len1 = length(a)
            if(len1==0)
                return -1
            else if(len1==1)
                return s+1

            len2 = length(a[len1])
            len3 = length(a[len1]+1)

            head = join(a, 1, len1-1)
            tail = sprintf("%0*d", len2, (a[len1]+1)%(10^len2))

            if(len2==len3)
                return head "." tail
            else
                return inc(head) "." tail
        }

        function join(a, x, y,    s)
        {
            for(i=x; i<y; i++)
                s = s a[i] "."
            return s a[y]
        }' $oldv)

        echo "newv: $newv"

        git tag -a "v$newv" -m "Automatically Generated Version $newv"
        git push --follow-tags

      shell: bash
